### ISSUE TITLE
Impossible to install hashformers

### ISSUE THREAD

**Issue by czanoli** [ruanchaves/hashformers#38]
I'm trying to install hashformers by using pip install hashformers but it remains stuck during packages installation and then yields the following error:

  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
visions 0.7.6 requires pandas>=2.0.0, but you have pandas 1.5.3 which is incompatible.
Successfully installed accelerate-0.25.0 aiohttp-3.9.5 aiosignal-1.3.1 frozenlist-1.4.1 fsspec-2024.6.0 hashformers-2.0.0 huggingface-hub-0.23.4 minicons-0.2.44 mpmath-1.3.0 multidict-6.0.5 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.20.5 nvidia-nvjitlink-cu12-12.5.40 nvidia-nvtx-cu12-12.1.105 openai-0.28.1 pandas-1.5.3 regex-2024.5.15 
safetensors-0.4.3 sympy-1.12.1 tenacity-8.4.2 tokenizers-0.19.1 torch-2.3.1 transformers-4.41.2 triton-2.3.1 twitter-text-python-1.1.1 urllib3-1.26.19 yarl-1.9.4

**Comment by ruanchaves** [comment]
Hashformers is currently compatible with Python 3.10.12, which is supported on Colab. If you're running a another Python version (likely above 3.10), you may encounter issues.

I've successfully installed the library on both Colab and my local machine using Python 3.10.12 without any problems.

I'll update the project README to include this Python version requirement. If you continue to experience issues after switching to the correct version, please feel free to reopen this issue.
